"""add_api_id_to_stores

Revision ID: 1423fd809e0b
Revises: d05d160f7b38
Create Date: 2025-12-31 11:49:26.776579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1423fd809e0b'
down_revision: Union[str, Sequence[str], None] = 'd05d160f7b38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('api_id', sa.String(length=255), nullable=True))
    op.create_unique_constraint('uq_store_chain_api_id', 'stores', ['chain', 'api_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_store_chain_api_id', 'stores', type_='unique')
    op.drop_column('stores', 'api_id')
    # ### end Alembic commands ###
