"""add_store_unique_constraint

Revision ID: d05d160f7b38
Revises: 4996a1644165
Create Date: 2025-12-22 23:54:40.872031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd05d160f7b38'
down_revision: Union[str, Sequence[str], None] = '4996a1644165'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop old constraint if it exists
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    constraints = inspector.get_unique_constraints('stores')
    if any(c['name'] == 'stores_chain_url_unique' for c in constraints):
        op.drop_constraint('stores_chain_url_unique', 'stores', type_='unique')

    # Create new constraint
    op.create_unique_constraint('uq_store_chain_name', 'stores', ['chain', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_store_chain_name', 'stores', type_='unique')
    op.create_unique_constraint(op.f('stores_chain_url_unique'), 'stores', ['chain', 'url'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
